from django.urls import path
from . import views

urlpatterns = [
    path('', views.user_dashboard, name='user_dashboard'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('take_quiz/<int:assignment_id>/', views.take_quiz, name='take_quiz'),
    path('submit_quiz/<int:assignment_id>/', views.submit_quiz, name='submit_quiz'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.password_reset_request_view, name='password_reset_request'),
    path('password-reset/confirm/', views.password_reset_confirm_view, name='password_reset_confirm'),
    path('aidadminpage/', views.aidadminpage, name='aidadminpage'),
    path('aidadminpage/add_theme/', views.add_theme, name='add_theme'),
    path('aidadminpage/delete_theme/<int:id>/', views.delete_theme, name='delete_theme'),
    path('aidadminpage/add_subject/', views.add_subject, name='add_subject'),
    path('aidadminpage/delete_subject/<int:id>/', views.delete_subject, name='delete_subject'),
    path('aidadminpage/add_quiz/', views.add_quiz_to_theme, name='add_quiz'),
    path('aidadminpage/add_quiz_to_theme/', views.add_quiz_to_theme, name='add_quiz_to_theme'),
    path('aidadminpage/delete_quiz/<int:id>/', views.delete_quiz, name='delete_quiz'),
    path('aidadminpage/add_question/', views.add_question, name='add_question'),
    path('aidadminpage/delete_question/<int:id>/', views.delete_question, name='delete_question'),
    path('aidadminpage/add_answer/', views.add_answer, name='add_answer'),
    path('aidadminpage/delete_answer/<int:id>/', views.delete_answer, name='delete_answer'),
    path('aidadminpage/assign_quiz/', views.assign_quiz, name='assign_quiz'),
    path('aidadminpage/add_user/', views.add_user, name='add_user'),
    path('aidadminpage/edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('aidadminpage/delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('aidadminpage/send_verification_code/', views.admin_send_verification_code, name='admin_send_verification_code'),
    path('aidadminpage/verify_code_only/', views.admin_verify_code_only, name='admin_verify_code_only'),
    path('aidadminpage/verify_and_reset_password/', views.admin_verify_and_reset_password, name='admin_verify_and_reset_password'),
    path('aidadminpage/update_profile/', views.admin_update_profile, name='admin_update_profile'),
    path('view_results/<int:assignment_id>/', views.view_results, name='view_results'),
]
