# Generated by Django 6.0.3 on 2026-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_engine', '0005_userprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
